### PR TITLE
Yahoo data script improvements

### PR DESCRIPTION
**Pull request by ipl31**
Hello, I am taking the coursera class and made some improvements to the yahoo data script:
1. removed unused sys import
2. fixed typo in comment, line 20 missing "not"
3. removed use of symbol_name, it was duplicating the data in $symbol for no obvious reason
4. moved the URL into its own variable so you can optionally add a "print url" if debugging
5. Not incrementing the miss url counter when catching urllib2.HTTPError
6. Change all print/log messages to use ".format()" instead of string concatenation, generally more robust.
7. Improve the parsing of the symbols.txt file. In my experience (on OSX) it did not handle whitespace after symbol names (they got URL encoded as "+") and it did not handle blank like at the end of the file. It handles those situations now.

### CODE REVIEW

**Comment by sb2nov** [comment]
The reason for using symbol_name is that Yahoo names index symbols starting with ^SPX. While Google and other data sources use $SPX. It was created to maintain consistency across all platforms over the ticker names.

**Comment by sb2nov** [comment]
Btw, Thanks for the improvements in the code.

**Comment by ipl31** [comment]
Ah, I see. I can refactor the patch to take that into account.

**Comment by ipl31** [comment]
Also one thing I left out of the original Pull Request description is that I casted symbol to STR in the read data method so it did not be casted later on.

**Pull request merged**
